### ISSUE TITLE
Rename rawValueBone to just rawBone

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#259]
We have a stringBone, a relationalBone, a fileBone... and now a rawValueBone? Why isn't this just be called rawBone, to comply with the already existing naming convention?  Or, let's rename stringBone, relationalBone, fileBone ... into stringValueBone, relationalValueBone and fileValueBone...

The type should be changed to "raw" instread of "rawvalue" as well.

**Comment by tsteinruecken** [comment]
Same here, the window for non-necessary breaking changes for ViUR3 is closed as it has landed in production. As this is a new feature and im not aware of it being used yet we might make an exception here if everybody is *very* unhappy with this, otherwise i'd keep it. (In my opinion that name is fine, if you see a stringBone or colorBone you know whats inside, that's not such descriptive with "raw") @XeoN-GHMB @AchimSchumacher @skoegl @sveneberth ?
