### ISSUE TITLE
How to retrieve `downloadUrl` of derived images?

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#506]
This topic was discussed lately. A FileBone has derives, but in the `json`-renderer there's no way to get these derived `downloadUrl`s except for the original file which is injected along with the `dlkey`. There's currently no solution or workaround. In the `html`-renderer, there's a built-in Jinja function to retrieve derived URLs for a given file. A solution for this needs to be found for json-renderer or by using an externally callable function for retrieving the URL.

**Comment by theVAX** [comment]
In my opinion, for files that are public, i.e. have no expiry period, the signed download urls, including those of the preview images etc., should be stored directly on the filebone and also be part of the server response. Otherwise, paths should be provided under which the download urls can be retrieved.

**Comment by phorward** [comment]
Is this fixed by #1241?

**Comment by phorward** [comment]
Seen as fixed by #1305, but #1290 also refers to it.
