### ISSUE TITLE
Vi does not show Modules, when same named function is defined before

### ISSUE THREAD

**Issue by Grashalmbeisser** [viur-framework/viur-core#542]
While Debugging, we noticed that a function, with the same name as a Module and Skeleton, is instanciated first when starting the Server and therefore breaks the Vi.

 By Changing the functions name, we where able to fix the problem.

**Comment by phorward** [comment]
Can you please provide an example, I don't understand this issue.

**Comment by sveneberth** [comment]
> Can you please provide an example, I don't understand this issue.

Let's talk about this friday in the viur meeting. This isn't really an error in the core. But maybe we can think about another module-registration or improve the module auto importer in the base.

---

### To clarify the issue:

If you define a module in your project _modules_ package (directory) like this:
```py
# test.py
class Test(List):
    ...
```
and now u define a method with the same name in lowercase (the same name as the [viur-base module auto importer](https://github.com/viur-framework/viur-base/blob/7e1b4a7a57ec52cf06bc6f332a1acb3d21a5149a/deploy/modules/__init__.py) would import the module above):
```py
# utils.py
def test():
   ...
```

#### What (could) happen now?
```py
DEBUG    2022-11-09 19:13:21,881 __init__.py:32] Importing <class 'modules.test.Test'> as test
DEBUG    2022-11-09 19:13:21,890 __init__.py:32] Importing <function test at 0x7fb329e7f1c0> as test
```
The test module will be shadowed/overwritten in `_viurModules` by the function. The order of the imports is depending on the result of `os.listdir()` which hasn't defined a stable order (so it's probably depending on the file system).

This can also happen if you import in the modules a method from outside, like:
```py
# deploy/modules/my_other_module.py
from utils import test
```
```py
# deploy/utils.py
def test():
    ...
```

So the helper function (which is/should not be exposed will be ignore in the core start-up (in _mapModule()_).

---
### conclusion
Don't define or import anything else in modules with the same name as a module. Otherwise the auto module import, depending on the order, wouldn't import the module. And the module would not be available in ViUR.

**Comment by phorward** [comment]
This problem relates to  viur-framework/viur-base#72 and is not relevant to viur-core.
